/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Noor Aldeen Muneer
 */
public class InformationAboutProduct extends javax.swing.JFrame {

    /**
     * Creates new form InformationAboutProduct
     */
    String Method,Server;

    public InformationAboutProduct(String method,String server) {
        initComponents();
        this.Method=method;
        this.Server=server;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prodidsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 220));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Product id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 37, 91, 32));

        prodidsearch.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        prodidsearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(prodidsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 36, 138, 32));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 37, 92, 32));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product id", "Name", "Amount", "Price / item ($)", "Price / item (EUR)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 789, 93));

        jPanel1.setBackground(new java.awt.Color(240, 197, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.Server.equals("PHP Server")){
        if(this.Method.equals("GET"))sendData_GET("http://localhost/inventorysystem/PHP_Server.php");
        else sendData_POST("http://localhost/inventorysystem/PHP_Server.php");
        }
        else{
        if(this.Method.equals("GET"))sendData_GET("http://localhost:8085/InventorySystemServlet/Server");//set servlet url
        else sendData_POST("http://localhost:8085/InventorySystemServlet/Server");//set servlet url
        }
        jTable1.setRowHeight(60);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.red);
        jTable1.setBackground(Color.CYAN);
        jTable1.setForeground(Color.WHITE);
        jTable1.setSelectionBackground(Color.WHITE);
        jTable1.setSelectionForeground(Color.BLACK);
        jTable1.setFont(new Font("Comic Sans MS",Font.ITALIC,30));
        TableColumnModel mod1=jTable1.getColumnModel();
        TableColumn TC=mod1.getColumn(1);
        TC.setPreferredWidth(300);
    }//GEN-LAST:event_jButton1ActionPerformed

    void sendData_GET(String url) {
        String SS="";
        DataInputStream dis;
        String prodid = this.prodidsearch.getText().trim();
        try {
            String str = url+"?ProdIDSearch="+prodid;
            URL u = new URL(str);
            dis = new DataInputStream(u.openConnection().getInputStream());
            URLConnection myConn = u.openConnection();
            InputStream is = myConn.getInputStream();
            int b;
            while ((b = is.read()) != -1) {
                    SS = SS + (char) b;
            }
            System.out.println(SS);
                    String [] res = SS.split("!");
                    if(res[0].equals("found"))
                    {
                        String [] items =res[1].split(":");
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setRowCount(0);
                        model.addRow(items);
//                        JOptionPane.showMessageDialog(null,"update successfuly");
                    }
                    else if(res[0].equals("notfound"))
                    {
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setRowCount(0);
                        JOptionPane.showMessageDialog(null,"Not found the product");
                    }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
        
    String dataStr = "";
    String contentStr = "application/x-www-form-urlencoded";

    public void addParameter(String ps, String vs) {
        if (ps == null || vs == null || ps.length() == 0 || vs.length() == 0) {
            return;
        }
        if (dataStr.length() > 0) {
            dataStr += "&";
        }
        try {
            dataStr += ps + "=" + URLEncoder.encode(vs, "ASCII");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
        void sendData_POST(String url) {
        dataStr = "";
        OutputStream os;
        InputStream is;
         String prodid = this.prodidsearch.getText().trim();
        addParameter("ProdIDSearch", prodid);
        String urlStr = url;
        String SS = "";
        try {
            URL myURL = new URL(urlStr);
            URLConnection myConn = myURL.openConnection();
            myConn.setDoOutput(true);
            myConn.setDoInput(true);
            myConn.setRequestProperty("Content-Type", contentStr);
            myConn.setUseCaches(false);
            BufferedOutputStream out = new BufferedOutputStream(myConn.getOutputStream());
            out.write(dataStr.getBytes());
            out.close();
            int b = -1;
            is = myConn.getInputStream();
            while ((b = is.read()) != -1) {
                SS = SS + (char) b;
            }
           System.out.println(SS);
                    String [] res = SS.split("!");
                    if(res[0].equals("found"))
                    {
                        String [] items =res[1].split(":");
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setRowCount(0);
                        model.addRow(items);
//                        JOptionPane.showMessageDialog(null,"update successfuly");
                    }
                    else if(res[0].equals("notfound"))
                    {
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setRowCount(0);
                        JOptionPane.showMessageDialog(null,"Not found the product");
                    }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField prodidsearch;
    // End of variables declaration//GEN-END:variables
}
