/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import javax.swing.JOptionPane;

/**
 *
 * @author Noor Aldeen Muneer
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    String Method,Server,LAT;
    int Empid;
    public MainPage(String method,String server,int eid,String lat) {
        initComponents();
        this.Method=method;
        this.Server=server;
        Empid=eid;
        LAT=lat;
        LastAccessTime.setText(lat);
        
        try {
        dataStr = "";
        OutputStream os;
        InputStream is;
        addParameter("Empselid", ""+Empid);
        String urlStr="";
        if(Server.equals("PHP Server"))
            urlStr ="http://localhost/inventorysystem/PHP_Server.php";
        else
            urlStr="http://localhost:8085/InventorySystemServlet/Server";
        URLConnection myConn = null;
        if(this.Method.equals("GET"))
        {
            urlStr+="?"+dataStr;
            System.out.println(urlStr);
            System.out.println("..............................");
            URL myURL = new URL(urlStr);
            DataInputStream dis = new DataInputStream(myURL.openConnection().getInputStream());
             myConn = myURL.openConnection();
        }
        else if(this.Method.equals("POST")){
        URL myURL = new URL(urlStr);
            myConn = myURL.openConnection();
            myConn.setDoOutput(true);
            myConn.setDoInput(true);
            myConn.setRequestProperty("Content-Type", contentStr);
            myConn.setUseCaches(false);
            BufferedOutputStream out = new BufferedOutputStream(myConn.getOutputStream());
            out.write(dataStr.getBytes());
            out.close();
            int b = -1;
            is = myConn.getInputStream();
            String SS="";
            while ((b = is.read()) != -1) {
                SS = SS + (char) b;
            }
        }
        }catch(Exception e){
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LastAccessTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prodid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(370, 190));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LastAccessTime.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(LastAccessTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Product id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        prodid.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        prodid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(prodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Last access time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 30));

        jPanel1.setBackground(new java.awt.Color(240, 197, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setText("Show All Product in Inventory ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 280, 40));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setText("Show Information about a Product ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("insert item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 150, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Withdraw item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, 30));

        Amount.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 640, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new InformationAboutProduct(this.Method,this.Server).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ShowAllProduct(this.Method,this.Server).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.Server.equals("PHP Server")){
        if(Method=="GET") 
            sendData_GET("add","http://localhost/inventorysystem/PHP_Server.php");
        else  
            sendData_POST("add","http://localhost/inventorysystem/PHP_Server.php");
        }
        else{
         if(Method=="GET") 
            sendData_GET("add","http://localhost:8085/InventorySystemServlet/Server");//add url servlet
        else  
            sendData_POST("add","http://localhost:8085/InventorySystemServlet/Server");//add url servlet
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.Server.equals("PHP Server")){
        if(Method=="GET")
            sendData_GET("delete","http://localhost/inventorysystem/PHP_Server.php");
        else
            sendData_POST("delete","http://localhost/inventorysystem/PHP_Server.php");
        }
        else{
        if(Method=="GET")
            sendData_GET("delete","http://localhost:8085/InventorySystemServlet/Server");//add url servlet
        else
            sendData_POST("delete","http://localhost:8085/InventorySystemServlet/Server");//add url servlet
        }
    }//GEN-LAST:event_jButton2ActionPerformed
void sendData_GET(String operation,String url) {
        String SS="";
        DataInputStream dis;
        String prodid = this.prodid.getText().trim();
        String amount = this.Amount.getText().trim();
        try {
            String str =url+"?ProdID="+prodid+"&Ammount="+amount+"&status="+operation;
            URL u = new URL(str);
            URLConnection myConn = u.openConnection();
            dis = new DataInputStream(myConn.getInputStream());
            
            InputStream is = myConn.getInputStream();
            int b;
            while ((b = is.read()) != -1) {
                    SS = SS + (char) b;
            }
           if(SS.equals("found")){
            JOptionPane.showMessageDialog(null,"update successfuly");
           }
           else{
            JOptionPane.showMessageDialog(null,"the product not found","",JOptionPane.WARNING_MESSAGE);
           }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
        
    String dataStr = "";
    String contentStr = "application/x-www-form-urlencoded";

    public void addParameter(String ps, String vs) {
        if (ps == null || vs == null || ps.length() == 0 || vs.length() == 0) {
            return;
        }
        if (dataStr.length() > 0) {
            dataStr += "&";
        }
        try {
            dataStr += ps + "=" + URLEncoder.encode(vs, "ASCII");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
        void sendData_POST(String operation,String url) {
        dataStr = "";
        OutputStream os;
        InputStream is;
         String prodid = this.prodid.getText().trim();
        String amount = this.Amount.getText().trim();
        addParameter("ProdID", prodid);
        addParameter("Ammount", amount);
        addParameter("status", operation);
        String urlStr = url;
        String SS = "";
        try {
            URL myURL = new URL(urlStr);
            URLConnection myConn = myURL.openConnection();
            myConn.setDoOutput(true);
            myConn.setDoInput(true);
            myConn.setRequestProperty("Content-Type", contentStr);
            myConn.setUseCaches(false);
            BufferedOutputStream out = new BufferedOutputStream(myConn.getOutputStream());
            out.write(dataStr.getBytes());
            out.close();
            int b = -1;
            is = myConn.getInputStream();
            while ((b = is.read()) != -1) {
                SS = SS + (char) b;
            }
           if(SS.equals("found")){
            JOptionPane.showMessageDialog(null,"update successfuly");
           }
           else{
            JOptionPane.showMessageDialog(null,"the product not found","",JOptionPane.WARNING_MESSAGE);
           }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JLabel LastAccessTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField prodid;
    // End of variables declaration//GEN-END:variables
}
