/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import javax.swing.JOptionPane;

/**
 *
 * @author Noor Aldeen Muneer
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    String Method,Server,LAT;
    int Empid;
    InventorySystem Invs=new InventorySystem();
    public MainPage(String method,String server,String lat) {
        initComponents();
        this.Method=method;
        this.Server=server;
        LAT=lat;
        LastAccessTime.setText(lat);
    }
    public MainPage(String method,String server,int eid,String lat) {
        initComponents();
        this.Method=method;
        this.Server=server;
        Empid=eid;
        LAT=lat;
        LastAccessTime.setText(lat);
        String namedata="Empselid#";
        String data=""+Empid+"#";
        if(this.Server.equals("PHP Server")){
        if(this.Method.equals("POST")){
        Invs.sendData_POST(namedata,data,"http://localhost/inventorysystem/PHP_Server.php");
        }
        else{
        Invs.sendData_GET("http://localhost/inventorysystem/PHP_Server.php?Empselid="+Empid);
        }
        }
        else{
        if(this.Method.equals("POST")){
        Invs.sendData_POST(namedata,data,"http://localhost:8085/InventorySystemServlet/Server");
        }
        else{
        Invs.sendData_GET("http://localhost:8085/InventorySystemServlet/Server?Empselid="+Empid);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        prodid = new javax.swing.JTextField();
        LastAccessTime = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(370, 190));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 197, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Product id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        prodid.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        prodid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(prodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 30));

        LastAccessTime.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPanel1.add(LastAccessTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 230, 30));

        jButton3.setBackground(new java.awt.Color(178, 152, 220));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setText("Show All Product in Inventory ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 280, 40));

        jButton4.setBackground(new java.awt.Color(178, 152, 220));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setText("Show Information about a Product ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 40));

        jButton1.setBackground(new java.awt.Color(178, 152, 220));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("insert item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 140, 30));

        jButton2.setBackground(new java.awt.Color(178, 152, 220));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Withdraw item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 30));

        Amount.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Amount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Last access time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 30));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 285, 420, 30));

        jButton6.setBackground(new java.awt.Color(178, 152, 220));
        jButton6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton6.setText("LogOut");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 230, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new InformationAboutProduct(this.Method,this.Server,this.LAT).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ShowAllProduct(this.Method,this.Server,this.LAT).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
public static boolean isNumeric(String str) { 
  try {  
    Double.parseDouble(str);  
    return true;
  } catch(NumberFormatException e){  
    return false;  
  }  
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String result="";
        if(prodid.getText().isEmpty()||Amount.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "please fill all fields", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else if(!isNumeric(Amount.getText())||!isNumeric(prodid.getText())){
        JOptionPane.showMessageDialog(null, "please Enter data with correct formate", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else if(this.Server.equals("PHP Server")){
            String namedata="ProdID#Ammount#status";
            String data=""+prodid.getText()+"#"+Amount.getText()+"#add";
        if(Method.equals("GET")) 
            result=Invs.sendData_GET("http://localhost/inventorysystem/PHP_Server.php?ProdID="+prodid.getText()+"&Ammount="+Amount.getText()+"&status=add");
        else  
            result=Invs.sendData_POST(namedata,data,"http://localhost/inventorysystem/PHP_Server.php");
        }
        else{
         String namedata="ProdID#Ammount#status";
         String data=""+prodid.getText()+"#"+Amount.getText()+"#add";
        if(Method.equals("GET")) 
            result=Invs.sendData_GET("http://localhost:8085/InventorySystemServlet/Server?ProdID="+prodid.getText()+"&Ammount="+Amount.getText()+"&status=add");
        else  
            result=Invs.sendData_POST(namedata,data,"http://localhost:8085/InventorySystemServlet/Server");
        }
        if(result.equals("found")){
        JOptionPane.showMessageDialog(null,"update successfuly");
        }
        else if(!result.isEmpty()){
        JOptionPane.showMessageDialog(null,"the product not found","",JOptionPane.WARNING_MESSAGE);
        }
        prodid.setText("");
        Amount.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String result="";
        if(prodid.getText().isEmpty()||Amount.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "please fill all fields", "", JOptionPane.WARNING_MESSAGE);
        }
        else if(!isNumeric(Amount.getText())||!isNumeric(prodid.getText())){
        JOptionPane.showMessageDialog(null, "please Enter data with correct formate", "", JOptionPane.WARNING_MESSAGE);
        }
        else if(this.Server.equals("PHP Server")){
        String namedata="ProdID#Ammount#status";
            String data=""+prodid.getText()+"#"+Amount.getText()+"#delete";
        if(Method=="GET") 
            result=Invs.sendData_GET("http://localhost/inventorysystem/PHP_Server.php?ProdID="+prodid.getText()+"&Ammount="+Amount.getText()+"&status=delete");
        else  
            result=Invs.sendData_POST(namedata,data,"http://localhost/inventorysystem/PHP_Server.php");
        }
        else{
        String namedata="ProdID#Ammount#status";
            String data=""+prodid.getText()+"#"+Amount.getText()+"#delete";
        if(Method=="GET") 
            result=Invs.sendData_GET("http://localhost:8085/InventorySystemServlet/Server?ProdID="+prodid.getText()+"&Ammount="+Amount.getText()+"&status=delete");
        else  
            result=Invs.sendData_POST(namedata,data,"http://localhost:8085/InventorySystemServlet/Server");
        }
        if(result.equals("found")){
        JOptionPane.showMessageDialog(null,"update successfuly");
        }
        else if(!result.isEmpty()){
        JOptionPane.showMessageDialog(null,"the product not found","",JOptionPane.WARNING_MESSAGE);
        }
        prodid.setText("");
        Amount.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new MainPage(this.Method, this.Server, this.LAT).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new SignIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JLabel LastAccessTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField prodid;
    // End of variables declaration//GEN-END:variables
}
