/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import javax.swing.JOptionPane;
//http://localhost:8085/inventorysystemServlet/
/**                     
 *
 * @author Noor Aldeen Muneer
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ServerType = new javax.swing.JComboBox<>();
        Method = new javax.swing.JComboBox<>();
        Password = new javax.swing.JTextField();
        EmployeeID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 150));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 197, 220));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ServerType.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ServerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PHP Server", "Servlet" }));
        jPanel1.add(ServerType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 130, 33));

        Method.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GET", "POST" }));
        Method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodActionPerformed(evt);
            }
        });
        jPanel1.add(Method, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 130, 30));

        Password.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, 30));

        EmployeeID.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        EmployeeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIDActionPerformed(evt);
            }
        });
        jPanel1.add(EmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 130, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 270, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Method");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Employee ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 120, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 400, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 400, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 400, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 400, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Server");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(ServerType.getSelectedItem().toString().equals("PHP Server")&&Method.getSelectedItem().toString().equals("GET")){
        String val=sendData_GET("http://localhost/inventorysystem/PHP_Server.php");
        if(val.split("!")[1].equals("true")){
           MainPage M1= new MainPage("GET", "PHP Server",Integer.parseInt(EmployeeID.getText()),val.split("!")[0]);
           M1.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "information invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(ServerType.getSelectedItem().toString().equals("PHP Server")&&Method.getSelectedItem().toString().equals("POST")){
        String val=sendData_POST("http://localhost/inventorysystem/PHP_Server.php");
        if(val.split("!")[1].equals("true")){
            MainPage M1=new MainPage("POST", "PHP Server",Integer.parseInt(EmployeeID.getText()),val.split("!")[0]);
           M1.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "information invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(ServerType.getSelectedItem().toString().equals("Servlet")&&Method.getSelectedItem().toString().equals("GET")){
        String val=sendData_GET("http://localhost:8085/InventorySystemServlet/Server");
        if(val.split("!")[0].equals("true")){
            MainPage M1=new MainPage("GET", "Servlet",Integer.parseInt(EmployeeID.getText()),val.split("!")[1]);
           M1.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "information invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(ServerType.getSelectedItem().toString().equals("Servlet")&&Method.getSelectedItem().toString().equals("POST")){
        String val=sendData_POST("http://localhost:8085/InventorySystemServlet/Server");
        if(val.split("!")[0].equals("true")){
            MainPage M1=new MainPage("POST", "Servlet",Integer.parseInt(EmployeeID.getText()),val.split("!")[1]);
           M1.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null, "information invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    String sendData_GET(String url) {
        String SS="";
        DataInputStream dis;
        String Eid = this.EmployeeID.getText().trim();
        String Pass = this.Password.getText().trim();
        try {
            String str = url+"?EmpID="+Eid+"&Password="+Pass;
            URL u = new URL(str);
            dis = new DataInputStream(u.openConnection().getInputStream());
            URLConnection myConn = u.openConnection();
            InputStream is = myConn.getInputStream();
            int b;
            while ((b = is.read()) != -1) {
                    SS = SS + (char) b;
            }
            System.out.print(SS);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
return SS;
    }
    
        
    String dataStr = "";
    String contentStr = "application/x-www-form-urlencoded";

    public void addParameter(String ps, String vs) {
        if (ps == null || vs == null || ps.length() == 0 || vs.length() == 0) {
            return;
        }
        if (dataStr.length() > 0) {
            dataStr += "&";
        }
        try {
            dataStr += ps + "=" + URLEncoder.encode(vs, "ASCII");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
        String sendData_POST(String url) {
        dataStr = "";
        OutputStream os;
        InputStream is;
        String Eid = this.EmployeeID.getText().trim();
        String Pass = this.Password.getText().trim();
        addParameter("EmpID", Eid);
        addParameter("Password", Pass);
        String urlStr = url;
        String SS = "";
        try {
            URL myURL = new URL(urlStr);
            URLConnection myConn = myURL.openConnection();
            myConn.setDoOutput(true);
            myConn.setDoInput(true);
            myConn.setRequestProperty("Content-Type", contentStr);
            myConn.setUseCaches(false);
            BufferedOutputStream out = new BufferedOutputStream(myConn.getOutputStream());
            out.write(dataStr.getBytes());
            out.close();
            int b = -1;
            is = myConn.getInputStream();
            while ((b = is.read()) != -1) {
                SS = SS + (char) b;
            }
           
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    return SS;
    }
    private void EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIDActionPerformed

    private void MethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MethodActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmployeeID;
    private javax.swing.JComboBox<String> Method;
    private javax.swing.JTextField Password;
    private javax.swing.JComboBox<String> ServerType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
